[package]
name = "better-hex-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[dependencies.better-hex]
path = ".."
features = ["_bench_internals"]

[[bin]]
name = "oracle"
path = "fuzz_targets/oracle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lengths"
path = "fuzz_targets/lengths.rs"
test = false
doc = false
bench = false
