[package]
name = "better-hex-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[dependencies.better-hex]
path = ".."
features = ["_bench_internals"]

[[bin]]
name = "oracle"
path = "fuzz_targets/oracle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lengths"
path = "fuzz_targets/lengths.rs"
test = false
doc = false
bench = false

[[bin]]
name = "encode_oracle"
path = "fuzz_targets/encode_oracle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_oracle"
path = "fuzz_targets/decode_oracle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "roundtrip"
path = "fuzz_targets/roundtrip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hex_str"
path = "fuzz_targets/hex_str.rs"
test = false
doc = false
bench = false
