[package]
name = "better-hex-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[features]
disable-simd = ["better-hex/disable-simd"]

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[dependencies.better-hex]
path = ".."
features = ["_bench_internals"]

[[bin]]
name = "oracle"
path = "fuzz_targets/oracle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "api"
path = "fuzz_targets/api.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hex_str"
path = "fuzz_targets/hex_str.rs"
test = false
doc = false
bench = false
