//! Miri-only driver shared by every fuzz target.
//!
//! `cargo miri run --bin <target>` needs a `main`; the libFuzzer C `main` is
//! only linked under the normal `cargo fuzz build` path. Each fuzz target keeps
//! `#![cfg_attr(not(miri), no_main)]` and adds a one-line `#[cfg(miri)] fn main`
//! that calls [`replay`] with the corpus subdirectory for that target.
//!
//! `replay` re-declares the `rust_fuzzer_test_input` symbol that `fuzz_target!`
//! emits at the bin's crate root and feeds it one corpus file per call. For
//! typed inputs (e.g. `|input: Input|`, `|data: &str|`) the macro handles
//! `Arbitrary` decoding / UTF-8 validation internally, so a raw `&[u8]` from
//! the file is the right shape regardless of the closure's declared type.

// `rust_fuzzer_test_input` is generated inside a `const _` block, so it's not
// reachable by name from the surrounding scope. The `#[unsafe(no_mangle)] pub
// extern "C" fn rust_fuzzer_test_input(&[u8]) -> i32` symbol *is* emitted into
// this bin, so we redeclare it via `extern`. `improper_ctypes` is fine —
// libfuzzer-sys itself notes "We do not actually cross the FFI bound here."
#[allow(improper_ctypes)]
unsafe extern "C" {
    fn rust_fuzzer_test_input(input: &[u8]) -> i32;
}

pub fn replay(default_dir: &str) {
    let dir = std::env::var("MIRI_CORPUS_DIR").unwrap_or_else(|_| default_dir.to_string());
    let mut count = 0usize;
    for entry in std::fs::read_dir(&dir).unwrap_or_else(|e| panic!("read_dir({dir:?}): {e}")) {
        let path = entry.expect("dir entry").path();
        if !path.is_file() {
            continue;
        }
        let data = std::fs::read(&path).unwrap_or_else(|e| panic!("read({path:?}): {e}"));
        // SAFETY: `rust_fuzzer_test_input` is the libfuzzer-sys entry point
        // generated by `fuzz_target!`; it accepts any byte slice.
        unsafe {
            rust_fuzzer_test_input(&data);
        }
        count += 1;
    }
    eprintln!("miri_replay: replayed {count} inputs from {dir}");
}
